spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medicine
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: create
  application:
    name: medicine-service
server:
  port: 8083
